---


- name: Install Bacula-fd (windows)
  ansible.windows.win_package:
    path: "{{ win_tempdir.path }}/{{ bacula_download_url_windows | basename }}"
    product_id: 'bacula-fd'
    arguments: /S

- name: Update config on client
  template:
    src: bacula-fd.conf.j2
    dest: "{{ bacula_root }}/bacula-fd.conf"
    mode: 0640
  vars:
    Directors:
      - "{{ bacula__default__filedaemon_director | default(bacula_filedaemon_director_var) }}"
      - Name: "bacula-dir-mon"
        Password: "{{ bacula_mon_password | default('changeme!') }}"
        Monitor: "yes"
    FileDaemon: "{{ bacula__common__filedaemon | combine(hostvars[inventory_hostname][bacula_filedaemon_var]|default({})) }}"
