---


- name: Install Bacula-fd (windows)
  ansible.windows.win_package:
    path: "{{ win_tempdir.path }}/{{ bacula_download_url_windows | basename }}"
    product_id: 'bacula-fd'
    arguments: /S

