# ---

# - name: "Remove client {{ item.name }}'s configuration"
#   file:
#     path: "/etc/bacula/clients.d/{{ item.name }}.conf"
#     state: absent
#   notify:
#     - Bacula-director restarted
#   no_log: "{{ bacula_no_log|bool }}"
