---

- name: "Remove client {{ item.name }}'s devices (only config)"
  file:
    path: "/etc/bacula/devs.d/{{ item.name }}-{{ policy.name | default('default') }}.conf"
    state: absent
  loop: "{{ item.policies | default([]) }}"
  loop_control:
    loop_var: policy
  no_log: "{{ bacula_no_log|bool }}"

- name: "Remove client {{ item.name }}'s configuration"
  file:
    path: "/etc/bacula/devs.d/{{ item.name }}-{{ policy.name | default('default') }}.conf"
    state: absent
  loop: "{{ item.policies | default([]) }}"
  loop_control:
    loop_var: policy
  notify:
    - Bacula-storage restarted
  no_log: "{{ bacula_no_log|bool }}"
