---

- name: "Clean {{ item.name }}'s devices (only config)"
  file:
    path: "/etc/bacula/devs.d/{{ item.name }}-{{ policy.name | default(bacula_policy_name_default) }}.conf"
    state: absent
  when: not (policy.enabled|bool)
  loop: "{{ item.policies | default([]) }}"
  loop_control:
    loop_var: policy
  notify:
    - Bacula-storage restarted
  no_log: "{{ bacula_no_log|bool }}"

- name: "Ensure client {{ item.name }}'s devices directory exists"
  file:
    path: "{{ bacula_sd_device }}/{{ item.name }}/{{ policy.name | default(bacula_policy_name_default) }}"
    state: directory
    owner: bacula
    group: bacula
    mode: 0740
  when:
    - policy.enabled|bool
  loop: "{{ item.policies | default([]) }}"
  loop_control:
    loop_var: policy
  notify:
    - Bacula-storage restarted
  no_log: "{{ bacula_no_log|bool }}"

- name: "Add bacula client {{ item.name }}'s devices config on storage"
  template:
    src: device.conf.j2
    dest: "/etc/bacula/devs.d/{{ item.name }}-{{ policy.name | default(bacula_policy_name_default) }}.conf"
    owner: bacula
    group: tape
    mode: 0640
  when: policy.enabled|bool
  loop: "{{ item.policies | default([]) }}"
  loop_control:
    loop_var: policy
  notify:
    - Bacula-storage restarted
  no_log: "{{ bacula_no_log|bool }}"
