---

- name: "Create client {{ item.name }} schedule"
  template:
    src: "schedules.d/template.conf.j2"
    dest: "/etc/bacula/schedules.d/{{ item.name }}.conf"
    owner: bacula
    group: tape
    mode: 0640
  vars:
    enabled: "{{ policy.enabled | default(true) }}"
    policy: "{{ policy.name | default(bacula__default__policy_name) }}"
    client: "{{ item.name | default('bacula') }}"
  tags:
    - molecule-idempotence-notest
  notify:
    - Bacula-director restarted
  no_log: "{{ bacula_no_log|bool }}"

- name: "Create client {{ item.name }} pool"
  template:
    src: "pools.d/template.conf.j2"
    dest: "/etc/bacula/pools.d/{{ item.name }}.conf"
    owner: bacula
    group: tape
    mode: 0640
  tags:
    - molecule-idempotence-notest
  notify:
    - Bacula-director restarted
  no_log: "{{ bacula_no_log|bool }}"

- name: "Create client {{ item.name }} policies (enabled: yes)"
  template:
    src: "{{ bacula_policies_template_folder }}/{{ policy.name }}.conf.j2"
    dest: "/etc/bacula/policy.d/{{ item.name }}-{{ policy.name }}.conf"
    owner: bacula
    group: tape
    mode: 0640
  vars:
    enabled: "{{ policy.enabled | default(true) }}"
    policy: "{{ policy.name | default(bacula__default__policy_name) }}"
    schedule: "{{ policy.schedule | default(bacula__default__schedule) }}"
    files_include: "{{ policy.files_include | default([]) }}"
    files_exclude: "{{ policy.files_exclude | default([]) }}"
    client: "{{ item.name | default('bacula') }}"
    storage: "{{ policy.storage | default('default') }}"
  tags:
    - molecule-idempotence-notest
  notify:
    - Bacula-director restarted
  no_log: "{{ bacula_no_log|bool }}"
