---

- set_fact:
    base_url: "{{ bacula_download_url }}/{{ ansible_distribution_release }}/amd64"

# https://www.bacula.org/bacula-binary-package-download/
- name: Fetch Packages file
  get_url:
    url: "{{ base_url }}/dists/{{ ansible_distribution_release }}/main/binary-amd64/Packages"
    dest: files/debs/Packages
    mode: u=r,g=r,o=

- name: Getting Filenames from Package file
  shell: cat files/debs/Packages | grep -Eo 'dists.*\.deb'
  register: filenames

- name: Fetching deb packages
  get_url:
    url: "{{ base_url }}/{{ item }}"
    mode: u=rx,g=rx,o=
  loop: "{{ filenames.output }}"
  when: filenames.rc == 0

# - include_tasks: secure.yml

# - name: Configure bacula-dir.conf
#   template:
#     src: bacula-dir.conf.j2
#     dest: /etc/bacula/bacula-dir.conf
#     owner: bacula
#     group: tape
#     mode: 0640
#   no_log: "{{ bacula_no_log|bool }}"
#   notify: Bacula-director restarted

# - name: Configure catalog.conf
#   template:
#     src: catalog.conf.j2
#     dest: /etc/bacula/conf.d/catalog.conf
#     owner: bacula
#     group: tape
#     mode: 0640
#   no_log: "{{ bacula_no_log|bool }}"
#   notify: Bacula-director restarted

# - name: Configure messages.conf
#   template:
#     src: messages.conf.j2
#     dest: /etc/bacula/conf.d/messages.conf
#     owner: bacula
#     group: tape
#     mode: 0640
#   no_log: "{{ bacula_no_log|bool }}"
#   notify: Bacula-director restarted

# - name: Configure storages.conf
#   template:
#     src: storages.conf.j2
#     dest: /etc/bacula/conf.d/storages.conf
#     owner: bacula
#     group: tape
#     mode: 0640
#   no_log: "{{ bacula_no_log|bool }}"
#   notify: Bacula-director restarted

# - include_tasks: telegram/cli-bot.yml
#   when: bacula_messages_telegram_enabled|bool

# - name: Configure bconsole.conf
#   template:
#     src: bconsole.conf.j2
#     dest: /etc/bacula/bconsole.conf
#     owner: bacula
#     group: tape
#     mode: 0640
#   no_log: "{{ bacula_no_log|bool }}"

# - name: Configure jobdef.conf
#   template:
#     src: jobdefs.conf.j2
#     dest: /etc/bacula/conf.d/jobdefs.conf
#     owner: bacula
#     group: tape
#     mode: 0640
#   no_log: "{{ bacula_no_log|bool }}"
#   notify: Bacula-director restarted

# - include_tasks: client-director-delete.yml
#   when:
#     - not (item.enabled|default(true)|bool)
#   with_items:
#     - "{{ bacula_clients }}"

# - include_tasks: client-director-add.yml
#   when:
#     - item.enabled|default(true)|bool
#   with_items:
#     - "{{ bacula_clients }}"
