---

- name: Install bacula-client
  include_tasks: install/bacula.yml
  when: bacula_filedaemon_install | default(true)
  vars:
    bacula_install_console: yes
    bacula_install_common: yes
    bacula_install_client: yes
    bacula_install_aligned: no
    bacula_install_gui: no
    bacula_install_database: no
