---

- name: Install bacula-client
  include_tasks: install-linux-fd.yml
  when: bacula_client_install | default(true) and (ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "Ubuntu" or bacula_omit_linux_family_check | default(false))

- name: Update config on client
  template:
    src: bacula-fd.conf.j2
    dest: "{{ bacula_root }}/etc/bacula-fd.conf"
    owner: "{{ bacula_owner }}"
    group: "{{ bacula_group }}"
    mode: 0640
  vars:
    Directors:
      - Name: "{{ bacula_director }}"
        Password: "{{ bacula_director.Password }}"
      - Name: "bacula-dir-mon"
        Password: "{{ bacula_mon_password | default('changeme!') }}"
        Monitor: "yes"
    FileDaemon: "{{ [ bacula__common__filedaemon | combine(hostvars[inventory_hostname][bacula_filedaemon_var]|default({})) ] }}"
    Messages: "{{ [ bacula__common__messages | combine(hostvars[inventory_hostname][bacula_filedaemon_var]|default({})) ] }}"
  notify:
    - bacula-fd configtest