---
# tasks file for matiferrigno.ansible-bacula

- name: Install server components
  include_tasks: components.yml
  when: not (bacula_only_client|default(false)|bool)
  tags:
    - server

- name: Install client component
  include_tasks: client.yml
  tags:
    - client
  when: bacula_only_client|default(false)|bool and item.enabled|default(true)|bool
  with_items:
    - "{{ bacula_client | default([]) }}"
