---
# tasks file for matiferrigno.ansible-bacula

- include_tasks: define.yml

- name: Install server components
  include_tasks: components.yml
  tags:
    - server

- name: Install client component
  include_tasks: client.yml
  tags:
    - client
  when:
    - item.enabled|bool
  with_items:
    - "{{ bacula_clients | default([]) }}"
