---

- name: Fetch clients on group "{{ bacula_client_group }}"
  set_fact:
    dyn_clients: |
      {% set cfg = bacula__common__clients | combine(hostvars[item][bacula_client_var] | default({})) %}
      {% set pName = cfg.Name | replace('#client#', item) if cfg.Name | d() else none %}
      {% set pAddress = cfg.Address | replace('#client_fqdn#', hostvars[item]['ansible_fqdn']) if cfg.Address | d() else none %}
      {% set client_changes = { 'Name': pName, 'Address': pAddress } %}
      {% for c in client_changes | dict2items %}
      {% if (cfg.update({ c.key: c.value }) if c.value is not none else cfg) %}{% endif %}
      {% endfor %}
      {{ dyn_clients | default([]) + [ cfg ] }}
  loop: "{{ groups[bacula_client_group] | default([]) }}"

- name: Fetch pools and define separate one for each client
  set_fact:
    pools: |
      {% set pName = item[0].Name | replace('#client#', item[1]) %}
      {% set pLabelFormat = item[0].LabelFormat | replace('#client#', item[1]) %}
      {{
        pools | default([]) + [item[0] | combine({ 'Name': pName, 'LabelFormat': pLabelFormat })]
      }}
  with_nested:
    - "{{ bacula_pools }}"
    - "{{ groups[bacula_client_group] | default([]) }}"

- name: Fetch jobs defined on each client
  set_fact:
    dyn_jobs: |
      {{
        dyn_jobs | default([]) + hostvars[item][bacula_client_jobs_var]
          if hostvars[item][bacula_client_jobs_var] | d()
            else dyn_jobs | default([])
      }}
  loop: "{{ groups[bacula_client_group] | default([]) }}"

- name: Fetch filesets defined on each client
  set_fact:
    dyn_filesets: |
      {%
        set hFilesets =
          hostvars[item][bacula_client_filesets_var] | default([])
            if hostvars[item][bacula_client_filesets_var] | d()
              else none
      %}
      {{
        dyn_filesets | default([]) +
          hFilesets | default([]) | map('combine',hFilesets,bacula__common__filesets)
            if hFilesets is not none
            else dyn_filesets | default([])
      }}
  loop: "{{ groups[bacula_client_group] | default([]) }}"

- name: Fetch storages on group "{{ bacula_storage_group }}"
  set_fact:
    dyn_storages: |
      {{
        dyn_storages | default([]) + hostvars[item][bacula_storage_var]
          if hostvars[item][bacula_storage_var] | d()
            else dyn_storages | default([])
      }}
  loop: "{{ groups[bacula_storage_group] | default([]) }}"

- name: Fetch catalogs on group "{{ bacula_catalog_group }}"
  set_fact:
    dyn_catalogs: |
      {{
        dyn_catalogs | default([]) + hostvars[item][bacula_catalog_var]
          if hostvars[item][bacula_catalog_var] | d()
            else dyn_catalogs | default([])
      }}
  loop: "{{ groups[bacula_catalog_group] | default([]) }}"

- name: Transform list of jobs
  set_fact:
    jobs: |
      {% set job = bacula__common__jobs | default([]) | combine(item[0]) %}
      {% set cName = item[0].Name | replace('#client#', item[1]) if item[0].Name | d() else none %}
      {% set cClient = item[0].Client | replace('#client#', item[1]) if item[0].Client | d() else none %}
      {% set cPool = item[0].Pool | replace('#client#', item[1]) if item[0].Pool | d() else none %}
      {% set cFullBackupPool = item[0].Full_Backup_Pool | replace('#client#', item[1]) if item[0].Full_Backup_Pool | d() else none %}
      {% set cDifferentialBackupPool = item[0].Differential_Backup_Pool | replace('#client#', item[1]) if item[0].Differential_Backup_Pool | d() else none %}
      {% set cIncrementalBackupPool = item[0].Incremental_Backup_Pool | replace('#client#', item[1]) if item[0].Incremental_Backup_Pool | d() else none %}
      {% set cFileSet = item[0].FileSet | replace('#client#', item[1]) if item[0].FileSet | d() else none %}
      {% set cJobDefs = item[0].JobDefs | replace('#client#', item[1]) if item[0].JobDefs | d() else none %}
      {% set cSchedule = item[0].Schedule | replace('#client#', item[1]) if item[0].Schedule | d() else none %}
      {% set job_changes = {
        'Name': cName,
        'Client': cClient,
        'FileSet': cFileSet,
        'JobDefs': cJobDefs,
        'Schedule': cSchedule,
        'Pool': cPool,
        'Full_Backup_Pool': cFullBackupPool,
        'Differential_Backup_Pool': cDifferentialBackupPool,
        'Incremental_Backup_Pool': cIncrementalBackupPool
        }
      %}
      {% for c in job_changes | dict2items %}
      {% if (job.update({ c.key: c.value }) if c.value is not none else job) %}{% endif %}
      {% endfor %}
      {{ jobs | default([]) + [ job ] }}
  with_nested:
    - "{{ bacula_jobs }}"
    - "{{ groups[bacula_client_group] | default([]) }}"
