---

- name: Update config on sd
  template:
    src: bacula-sd.conf.j2
    dest: "{{ bacula_root }}/etc/bacula-sd.conf"
    owner: "{{ bacula_owner }}"
    group: "{{ bacula_group }}"
    mode: 0640
  vars:
    Directors: "{{ [ bacula__default__storage_director ] + hostvars[inventory_hostname][bacula_storage_directors_var] | default([]) }}"
    Storage: "{{ bacula__common__storage | combine(hostvars[inventory_hostname][bacula_storage_var]|default({})) }}"
  notify:
    - bacula-fd configtest
