---
# handlers file for matiferrigno.ansible-bacula

- name: restart
  systemd:
    name: bacula-dir
    state: restarted
  when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "Ubuntu"

- name: bacula-dir configtest
  shell: "./bacula-dir -t"
  args:
    chdir: "{{ bacula_root }}/bin"
  changed_when: false
  when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "Ubuntu"

- name: bacula-sd configtest
  shell: "./bacula-sd -t"
  args:
    chdir: "{{ bacula_root }}/bin"
  changed_when: false
  when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "Ubuntu"

- name: bacula-fd configtest
  shell: "./bacula-fd -t"
  args:
    chdir: "{{ bacula_root }}/bin"
  changed_when: false
  when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "Ubuntu"
