---
# handlers file for matiferrigno.ansible-bacula

- name: restart
  systemd:
    name: bacula-dir
    state: restarted

- name: configtest
  shell: "./bacula-dir -t"
  args:
    chdir: "{{ bacula_root }}/bin"
  changed_when: false


- name: bacula-fd configtest
  shell: "./bacula-fd -t"
  args:
    chdir: "{{ bacula_root }}/bin"
  changed_when: false