---

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: debian10
    config_options:
      ssh.keep_alive: true
      synced_folder: true
    box: debian/contrib-buster64
    memory: 2048
    cpus: 2

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    links:
      group_vars: ../../tests/inventory/group_vars/
      host_vars: ../../tests/inventory/host_vars/
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_task, timer, yaml
