---

- hosts: all
  tasks:
  - name: Gathering info
    setup: {}

- hosts: bacula-client
  tasks:
    - include_role:
        name: ansible-role-bacula
        tasks_from: fd

- hosts: bacula-storage
  tasks:
    - include_role:
        name: ansible-role-bacula
        tasks_from: sd

- hosts: bacula-director
  tasks:
    - include_role:
        name: ansible-role-bacula
        tasks_from: dir
