---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: podman
platforms:
  - name: debian10
    image: geerlingguy/docker-debian10-ansible:latest
    command: /lib/systemd/systemd
    pre_build_image: false
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu2004
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    command: /lib/systemd/systemd
    pre_build_image: false
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    links:
      group_vars: ../../tests/inventory/group_vars/
      host_vars: ../../tests/inventory/host_vars/
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_task, timer, yaml
    ssh_connection:
      pipelining: false
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
