---

dependency:
  name: galaxy

driver:
  name: docker
platforms:
  - name: bacula.molecule
    image: docker.io/geerlingguy/docker-debian11-ansible:latest
    command: /lib/systemd/systemd
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: client.molecule
    image: docker.io/geerlingguy/docker-debian11-ansible:latest
    command: /lib/systemd/systemd
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  # lint:
  #   name: ansible-lint
  inventory:
    links:
      group_vars: ../../tests/inventory/group_vars/
      host_vars: ../../tests/inventory/host_vars/
      hosts: inventory.yml
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_task, timer, yaml
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  # ansible-lint .
